apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - dind-pvc.yaml
  - orchestrator-deployment.yaml
  - orchestrator-service.yaml
  - orchestrator-ingress.yaml
