{{- if and .Values.knowledgebase.enabled (not .Values.knowledgebase.config.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smithy.knowledgebase.fullname" . }}-secret
  labels:
    {{- include "smithy.labels" . | nindent 4 }}
    app.kubernetes.io/component: knowledgebase
type: Opaque
stringData:
  {{- with .Values.knowledgebase.config.openaiApiKey }}
  OPENAI_API_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.knowledgebase.config.vcsToken }}
  VCS_TOKEN: {{ . | quote }}
  {{- end }}
  {{- with .Values.knowledgebase.config.webhookSecret }}
  WEBHOOK_SECRET: {{ . | quote }}
  {{- end }}
{{- end }}
