apiVersion: v1
kind: Service
metadata:
  name: {{ include "smithy.orchestrator.fullname" . }}
  labels:
    {{- include "smithy.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
spec:
  type: {{ .Values.orchestrator.service.type }}
  selector:
    {{- include "smithy.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
  ports:
    - name: http
      port: {{ .Values.orchestrator.service.port }}
      targetPort: http
      protocol: TCP
