spring:
  application:
    name: knowledgebase-mcp
  profiles:
    active: ${AI_PROVIDER:ollama}
  ai:
    mcp:
      server:
        enabled: true
        capabilities:
          tool: true
          resource: false
          prompt: false
          completion: false
        protocol: streamable

server:
  port: ${SERVER_PORT:8000}
  shutdown: immediate

logging:
  level:
    root: INFO
    dev.smithyai.knowledgebase: DEBUG
