{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.smithy-ai",
    "module": "forgejo-client",
    "version": "14.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "forgejo-client-14.0.3.jar",
          "url": "forgejo-client-14.0.3.jar",
          "size": 2453769,
          "sha512": "ff0c0a0fec31fdbb7e61c6cd98101560d95243d7e319ed1785aee80cc16d063fbd656751de7bc25b73b4da5992b44c2691148da9e67f84ee3344b09fa558e1c7",
          "sha256": "22ccd3c61939b7176221a309ae8354953152d02d50966c9ef0f1767693d89055",
          "sha1": "ab6d65a98979ae60b54ce1fc63d1a34e8a3c2f0a",
          "md5": "420ebd000edce1e5734c8f04c5bc0b1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "io.gsonfire",
          "module": "gson-fire",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "jakarta.ws.rs",
          "module": "jakarta.ws.rs-api",
          "version": {
            "requires": "2.1.6"
          }
        },
        {
          "group": "org.openapitools",
          "module": "jackson-databind-nullable",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.18.0"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        }
      ],
      "files": [
        {
          "name": "forgejo-client-14.0.3.jar",
          "url": "forgejo-client-14.0.3.jar",
          "size": 2453769,
          "sha512": "ff0c0a0fec31fdbb7e61c6cd98101560d95243d7e319ed1785aee80cc16d063fbd656751de7bc25b73b4da5992b44c2691148da9e67f84ee3344b09fa558e1c7",
          "sha256": "22ccd3c61939b7176221a309ae8354953152d02d50966c9ef0f1767693d89055",
          "sha1": "ab6d65a98979ae60b54ce1fc63d1a34e8a3c2f0a",
          "md5": "420ebd000edce1e5734c8f04c5bc0b1f"
        }
      ]
    }
  ]
}
